name: Push to NuGet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}

      - name: Build solution and generate NuGet package
        run: |
          cd RpcLikeBlazor
          nuget.exe pack .nuspec
