name: Update NuGet package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Setup nuget
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}

      - name: Generate package and push
        run: |
          echo "package creating..."
          cd RpcLikeBlazor
          nuget pack .nuspec
          echo "package created"
          echo "pushing package..."
          nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
          echo "package pushed"
